const marvelHeroesWithHints = [
    ["doctorstrange", "Master of the Mystic Arts and the Sorcerer Supreme."],
    ["ironman", "Genius billionaire in an armored suit powered by an arc reactor."],
    ["captainamerica", "Super-soldier with a shield made of vibranium."],
    ["thor", "The god of thunder who wields the hammer Mjolnir."],
    ["hulk", "A scientist who transforms into a green rage monster with immense strength."],
    ["blackwidow", "A highly trained spy and combat expert."],
    ["spiderman", "A young hero with spider-like abilities and web-slinging."],
    ["antman", "Can shrink and grow in size using a special suit."],
    ["hawkeye", "A master archer with precise aim."],
    ["blackpanther", "King of Wakanda with enhanced senses and a vibranium suit."],
    ["scarletwitch", "Possesses powerful chaos magic and reality-warping abilities."],
    ["vision", "An android with the power of flight, density control, and a mind stone."],
    ["falcon", "Uses mechanical wings for flight and is an expert in aerial combat."],
    ["wintersoldier", "A super-soldier with a metal arm and highly trained combat skills."],
    ["captainmarvel", "Possesses cosmic powers and can fly through space."],
    ["starlord", "Leader of the Guardians of the Galaxy, with combat and piloting skills."],
    ["groot", "A sentient tree-like creature with regenerative powers."],
    ["rocketraccoon", "A genetically enhanced raccoon with tech expertise and a love for weapons."],
    ["drax", "A powerful warrior with a personal vendetta against Thanos."],
    ["gamora", "A skilled assassin and the adopted daughter of Thanos."],
    ["nebula", "A cybernetic assassin with a complex relationship with her sister, Gamora."],
    ["loki", "The god of mischief, known for illusion and trickery."],
    ["warmachine", "A military officer in a heavily armed Iron Man-style suit."],
    ["wasp", "A superhero with the ability to shrink and fly, alongside Ant-Man."],
    ["shangchi", "Master of martial arts and the mystical Ten Rings."],
    ["eternals", "An ancient group of immortal beings with various powers."]
];

const bollywoodHeroesWithHints = [
    ["shahrukhkhan", "Known as the King of Bollywood, famous for 'Dilwale Dulhania Le Jayenge'."],
    ["salmankhan", "Star of 'Bajrangi Bhaijaan' and 'Sultan'."],
    ["aamirkhan", "Actor in 'Dangal' and '3 Idiots', known for perfection."],
    ["akshaykumar", "Known for action-comedies like 'Housefull' and 'Khiladi'."],
    ["ranveersingh", "A versatile actor known for energetic roles in 'Padmaavat' and 'Gully Boy'."],
    ["hrithikroshan", "A dancing sensation and action star from 'Krrish' and 'War'."],
    ["ranbirkapoor", "Known for roles in 'Sanju' and 'Rockstar'."],
    ["ajaydevgn", "A serious and action-packed actor famous for 'Singham' and 'Tanhaji'."],
    ["amitabhbachchan", "The legendary actor known for 'Sholay' and 'Piku'."],
    ["varundhawan", "Star of 'Badrinath Ki Dulhania' and 'Street Dancer'."],
    ["sidharthmalhotra", "Known for his roles in 'Kapoor & Sons' and 'Shershaah'."],
    ["arjunkapoor", "Notable for performances in '2 States' and 'Namaste England'."],
    ["akshaye", "Famous for his roles in 'Sardar Udham' and 'Pati Patni Aur Woh'."],
    ["karthikaryan", "Known for his roles in 'Pyaar Ka Punchnama' and 'Sonu Ke Titu Ki Sweety'."],
    ["sushantsinghrajput", "Known for 'Chhichhore' and 'MS Dhoni: The Untold Story'."],
    ["saifalikhan", "Famous for roles in 'Omkara' and 'Tanhaji'."],
    ["johnabraham", "Known for his roles in 'Dhoom' and 'Batla House'."],
    ["vivekoberoi", "Notable for his performances in 'Company' and 'Saathiya'."],
    ["emraanhashmi", "Known for his roles in 'Murder' and 'Jannat'."],
    ["shahidkapoor", "Famous for 'Haider' and 'Kabir Singh'."],
    ["abhishekbachchan", "Notable for 'Guru' and 'Dhoom'."],
    ["bobbydeol", "Known for roles in 'Soldier' and 'Race 3'."],
    ["diljeitsingh", "Popular for his roles in 'Punjab 1984' and 'Good Newwz'."],
    ["prabhas", "Known for his work in 'Baahubali' and 'Saaho'."],
    ["nawazuddinsiddiqui", "Renowned for his performances in 'Gangs of Wasseypur' and 'Sacred Games'."],
    ["manojbajpayee", "Famous for his roles in 'Satya' and 'The Family Man'."],
    ["pankajtripathi", "Known for his roles in 'Stree' and 'Mirzapur'."],
    ["zaynmalik", "Not a Bollywood actor but a well-known figure in the entertainment industry."],
    ["salman", "Another name for Salman Khan, star of 'Kick' and 'Bajrangi Bhaijaan'."],
    ["ranvirsingh", "Another spelling for Ranveer Singh, known for 'Padmaavat' and 'Gully Boy'."],
    ["ranbirkapoor", "Another spelling for Ranbir Kapoor, known for 'Rockstar' and 'Sanju'."],
    ["ajay", "Another name for Ajay Devgn, known for 'Tanhaji' and 'Singham'."],
    ["amitabh", "Another name for Amitabh Bachchan, renowned for his roles in 'Sholay' and 'Paa'."]
];

const cricketerswithhints = [
    ["sachintendulkar", "Often referred to as the deity of cricket, this Indian legend set unparalleled records in both Test and ODI formats, particularly famous for his longevity and monumental career runs."],
    ["viratkohli", "This Indian batsman has shattered numerous records, including the most double centuries in Tests, and is renowned for his aggressive style and leadership in the shorter formats."],
    ["msdhoni", "A wicketkeeper-batsman with an iconic calm demeanor, he led India to two major global titles and is celebrated for his cool decision-making under pressure."],
    ["rohitsharma", "Holding the record for the highest number of double centuries in ODIs, this Indian opener is known for his explosive batting and successful stint as an IPL captain."],
    ["kapildev", "This dynamic all-rounder led India to its inaugural World Cup win in 1983, known for his revolutionary impact on Indian cricket and his pace bowling prowess."],
    ["yuvrajsingh", "This aggressive left-handed batsman is famous for his breathtaking six sixes in an over during a T20 World Cup, contributing significantly to India's 2011 World Cup win."],
    ["rahuldravid", "Known as 'The Wall' for his rock-solid technique, this Indian batsman was a mainstay in Test cricket, renowned for his resilience and technique."],
    ["anilkumble", "India's premier leg-spinner who dominated Test cricket with his meticulous accuracy, known for his aggressive leadership and historical match performances."],
    ["jaspritbumrah", "Famed for his exceptional death-bowling skills and unorthodox action, this Indian pacer is a crucial asset in all formats, especially in high-pressure situations."],
    ["hardikpandya", "This dynamic all-rounder brought a fresh flair to the Indian team with his explosive batting and useful medium-pace bowling, leading an IPL team to their first title."],
    ["ravindrajadeja", "Known for his exceptional fielding and impactful all-round performances, this Indian player excels in both batting and bowling, playing key roles in various matches."],
    ["souravganguly", "With his aggressive captaincy, this former Indian player is credited with transforming Indian cricket and earning the title 'Prince of Kolkata' for his leadership and batting."],
    ["zaheerkhan", "This left-arm fast bowler played a pivotal role in India's 2011 World Cup victory, known for his effective swing bowling in the crucial moments."],
    ["vvslaxman", "Famous for his stylish batting and a match-defining innings against Australia in 2001, this Indian batsman is known for his elegance and crucial contributions."],
    ["klrahul", "Renowned for his stylish technique and consistency in the IPL, this Indian opener is known for his versatile batting skills and solid performances."],
    ["shikhardhawan", "Known for his aggressive and prolific run-scoring in ICC tournaments, this Indian opener is recognized for his dynamic starts and impactful innings."],
    ["sureshraina", "One of the most dependable and explosive middle-order batsmen in the IPL, this Indian player is known for his aggressive style and crucial innings."],
    ["dineshkarthik", "A seasoned wicketkeeper-batsman, this Indian player is famous for his ability to finish matches with his explosive batting in limited-overs formats."],
    ["rishabhpant", "This fearless Indian wicketkeeper-batsman is celebrated for his aggressive and explosive batting style across all formats, making significant impacts in crucial games."],
    ["ashwinravichandran", "India's leading off-spinner, known for his strategic mastery and variations in all formats, he has been a key figure in India’s spin attack."],
    ["bhuvneshwar", "A bowler known for his skillful swing and control in the initial overs, this Indian pacer is essential for both ODI and T20 formats."],
    ["rashidkhan", "This Afghan spinner has become a T20 sensation with his innovative spin bowling and impactful performances in various leagues around the world."],
    ["andrerussell", "A powerful all-rounder from the West Indies, known for his explosive batting and key performances in the IPL, making him a sought-after player."],
    ["davidwarner", "This Australian opener is known for his aggressive and impactful batting, and has captained an IPL team to success with his explosive style."],
    ["abdevilliers", "Known as 'Mr. 360' for his ability to play shots all around the ground, this South African batsman is celebrated for his innovative batting in T20 leagues."],
    ["benstokes", "This English all-rounder is renowned for his match-winning performances, including his crucial innings in the 2019 World Cup final, showcasing his all-round capabilities."],
    ["patcummins", "Australia’s fast-bowling spearhead, recognized for his pace and leadership, has been a dominant force in international cricket and IPL alike."],
    ["jofraarcher", "This English pacer is known for his blistering speed and key performances in the IPL, making a significant impact with his aggressive bowling style."],
    ["kieronpollard", "A powerful all-rounder from the West Indies, this player is known for his match-winning capabilities and long-time success with Mumbai Indians in the IPL."],
    ["quintondekock", "A South African wicketkeeper-batsman known for his explosive and aggressive batting, making significant contributions at the top of the order."],
    ["stevesmith", "This Australian batsman is known for his technical proficiency and has been a consistent performer across formats, including his stint as captain."],
    ["kanewilliamson", "New Zealand’s calm and technically sound batsman, known for his steady performances and leadership qualities in international cricket."],
    ["sunilnarine", "A West Indian spinner renowned for his unorthodox bowling style and significant impact in T20 leagues, known for his mystery spin and success in the IPL."],
    ["trentboult", "This New Zealand left-arm swing bowler is famous for his early breakthroughs and impactful performances in white-ball cricket."],
    ["shreyasiyer", "An emerging leader in Indian cricket, known for his captaincy in the IPL and steady performances, making him a promising future star."],
    ["mayankagarwal", "A reliable Indian opener known for his consistent performances in domestic and international cricket, demonstrating his ability at the top of the order."],
    ["prithvishaw", "An aggressive young Indian opener, known for his explosive starts and impressive performances in domestic and international cricket."],
    ["sanjusamson", "A talented wicketkeeper-batsman leading his IPL team with his aggressive and flamboyant batting, known for his leadership and match-winning abilities."],
    ["ravibishnoi", "A young and promising leg-spinner for India, recognized for his impressive performances and potential in T20 cricket."],
    ["arshdeep", "An emerging left-arm pacer known for his death-bowling skills and effective performances in the IPL, adding depth to the Indian bowling attack."],
    ["devduttpadikkal", "A promising left-handed opener, known for his consistent performances in the IPL and his potential as a future star in Indian cricket."],
    ["shubmangill", "A young Indian batsman known for his solid technique and impressive performances in domestic and international cricket."],
    ["pradeepangad", "An emerging talent in Indian domestic cricket, known for his effective pace bowling and promising performances."],
    ["natarajans", "Known for his ability to bowl yorkers at will, this Indian left-arm pacer has made a significant impact in the T20 leagues with his death-bowling skills."],
    ["tejashwiyam", "A promising young Indian cricketer, known for his all-round capabilities and potential in domestic and international cricket."],
    ["harshalpatel", "Known for his variations and effective death-over bowling, this Indian pacer has been a key player in the IPL for his impressive performances."],
    ["csklegend", "A stalwart of the Chennai Super Kings, known for his consistent performances and leadership in the IPL."],
    ["rajasthansens", "A promising cricketer from Rajasthan, known for his impactful performances in domestic cricket and the IPL."],
    ["karanveer", "An effective spinner known for his skillful bowling and consistent performances in domestic cricket."],
    ["ishankishan", "A young wicketkeeper-batsman known for his aggressive batting and potential in the T20 format, making his mark in the IPL."],
    ["manishpandey", "A dependable Indian middle-order batsman, known for his steady performances in both domestic and international cricket."],
    ["mohammedsiraj", "A fast bowler known for his pace and aggression, making significant contributions to India's bowling attack and the IPL."],
    ["shahrukhkhan", "Known for his powerful hitting in the lower middle order, this player has made an impact with his performances in the IPL."],
    ["vijayshankar", "An all-rounder known for his useful contributions with both bat and ball, making him a valuable player in the T20 format."],
    ["aashishnehra", "A veteran left-arm pacer known for his experience and effective bowling in limited-overs cricket, especially in T20s."],
    ["deepakchahar", "Known for his swing bowling and effective powerplay spells, this Indian pacer has been a key player in the IPL and international cricket."],
    ["kagisorahul", "A promising South African cricketer, known for his pace and impact in domestic and international cricket."],
    ["arjuntendulkar", "The son of Sachin Tendulkar, known for his potential and performances in domestic cricket as an emerging talent."],
    ["yusufpathan", "An explosive all-rounder known for his powerful hitting and effective off-spin, making significant contributions in T20 leagues."],
    ["irfanpathan", "An all-rounder known for his swing bowling and lower-order batting, playing a key role in India's 2007 T20 World Cup victory."],
    ["mohammadnabi", "An Afghan all-rounder known for his effective spin bowling and impactful batting in T20 leagues."],
    ["hasanali", "A Pakistani fast bowler known for his aggressive bowling and contributions in limited-overs cricket."],
    ["fakharzaman", "A Pakistani opener known for his explosive batting and impactful performances in limited-overs formats."],
    ["sarfrazahmed", "A Pakistani wicketkeeper-batsman known for his leadership and contributions in various formats."],
    ["babarazam", "Pakistan's stylish batsman known for his consistent performances across all formats and his leadership skills."],
    ["shadabkhan", "A promising Pakistani all-rounder known for his leg-spin bowling and useful lower-order batting in limited-overs formats."],
    ["mushtaqahmed", "A former Pakistani leg-spinner known for his skillful spin bowling and contributions to various leagues."],
    ["chriswoakes", "An English all-rounder known for his effective pace bowling and useful lower-order batting in limited-overs formats."],
    ["liamlivingstone", "An English all-rounder known for his explosive batting and useful spin bowling in T20 formats."],
    ["johnnybairstow", "An English wicketkeeper-batsman known for his aggressive batting and key performances in limited-overs cricket."],
    ["georgedocker", "A promising English cricketer known for his effective pace bowling and contributions in domestic cricket."],
    ["kylejamieson", "A New Zealand fast bowler known for his height and pace, making significant impacts in international cricket."],
    ["timsouthee", "A New Zealand pacer known for his swing bowling and valuable contributions in both Test and limited-overs formats."],
    ["michaelstarce", "An Australian all-rounder known for his impactful performances in domestic and international cricket."],
    ["camerongreen", "A young Australian all-rounder known for his impressive batting and bowling, showing great potential in international cricket."],
    ["mitchellstar", "An Australian fast bowler known for his pace and impact in international cricket, especially in the shorter formats."],
    ["danielworrell", "A promising Australian pacer known for his effective bowling and contributions in domestic and international cricket."],
    ["brendonmccullum", "A former New Zealand captain known for his aggressive batting and impactful leadership in both Test and limited-overs formats."],
    ["rosstaylor", "A New Zealand batsman known for his consistency and contributions in all formats, making him one of the country's greats."],
    ["jeremybell", "A young New Zealand cricketer known for his promising performances and potential in domestic cricket."],
    ["aidenmarkram", "A South African batsman known for his solid technique and contributions across formats, showing great potential in international cricket."],
    ["quintondekock", "A South African wicketkeeper-batsman known for his explosive batting and key performances at the top of the order."],
    ["ngidilungisani", "A South African pacer known for his pace and effectiveness in limited-overs formats, making significant contributions."],
    ["daneparrison", "A promising South African fast bowler known for his pace and impact in domestic and international cricket."],
    ["harmersimon", "A South African spinner known for his effective bowling in domestic cricket and potential in international formats."],
    ["shanewarne", "An Australian leg-spinner renowned for his legendary spin bowling and significant impact in international cricket."],
    ["glennmaxwell", "An Australian all-rounder known for his explosive batting and useful spin bowling in T20 formats."],
    ["michaelclarke", "A former Australian captain known for his solid batting and leadership skills, contributing significantly across formats."],
    ["adamlyon", "An Australian off-spinner known for his consistency and key performances in Test cricket, making him a valuable player."],
    ["jamesfaulkner", "An Australian all-rounder known for his effective bowling and explosive lower-order batting in limited-overs formats."],
    ["mitchellmarsh", "An Australian all-rounder known for his powerful hitting and effective bowling in both domestic and international cricket."],
    ["moeenali", "An English all-rounder known for his spin bowling and useful batting, making significant contributions in various formats."],
    ["samcurran", "An English all-rounder known for his swing bowling and impactful performances in both domestic and international cricket."],
    ["adilrashid", "An English leg-spinner known for his wicket-taking ability and key performances in limited-overs formats."],
    ["saqibmahmood", "An English pacer known for his pace and impact in domestic and limited-overs cricket."],
    ["jofraarcher", "An English fast bowler known for his extreme pace and significant impact in T20 leagues and international cricket."],
    ["liamplunkett", "An English pacer known for his effective bowling in limited-overs formats, making crucial contributions."],
    ["jamestopley", "An English pacer known for his effective bowling and promising performances in domestic cricket."],
    ["shanewatson", "A former Australian all-rounder known for his explosive batting and useful bowling in T20 leagues and international cricket."],
    ["rohitsharma", "A leading Indian opener known for his record-breaking double centuries and success as an IPL captain."],
    ["harbhajansingh", "An experienced Indian off-spinner known for his match-winning performances and contributions across formats."],
    ["mohammadnabi", "An Afghan all-rounder known for his effective spin bowling and impactful batting in T20 leagues."],
    ["azharali", "A Pakistani batsman known for his solid technique and valuable contributions in Test cricket."],
    ["sarfrazahmed", "A Pakistani wicketkeeper-batsman known for his leadership and contributions in various formats."],
    ["shoaibmalik", "A Pakistani all-rounder known for his useful contributions with both bat and ball in limited-overs formats."],
    ["umargul", "A Pakistani fast bowler known for his effective pace bowling in limited-overs formats and key performances."],
    ["youniskhan", "A former Pakistani batsman known for his solid technique and key innings in Test cricket, including a World Cup win."],
    ["mohammadrafiq", "A Pakistani spinner known for his effective bowling in both Test and limited-overs formats."],
    ["javedmiandad", "A legendary Pakistani batsman known for his incredible batting performances and key innings in various formats."],
    ["wasimakram", "A Pakistani fast bowler known for his swing bowling and impactful performances in both domestic and international cricket."],
    ["waqaryounis", "A Pakistani pacer known for his reverse swing and significant contributions in Test and limited-overs cricket."],
    ["saeedajmal", "A Pakistani spinner known for his effective off-spin and key performances in limited-overs formats."],
    ["kamranakmal", "A Pakistani wicketkeeper-batsman known for his aggressive batting and valuable contributions across formats."],
    ["umarakmal", "A Pakistani batsman known for his aggressive style and key performances in domestic and international cricket."],
    ["shahidafridi", "A Pakistani all-rounder known for his explosive batting and effective spin bowling in T20 formats."],
    ["babarazam", "A stylish Pakistani batsman known for his consistent performances across all formats and leadership skills."],
    ["rahuldravid", "A legendary Indian batsman known for his rock-solid technique and crucial innings in Test cricket."],
    ["sunilgavaskar", "A former Indian opener known for his exceptional batting and significant contributions in Test cricket."],
    ["kapildev", "A former Indian all-rounder known for leading India to its first World Cup win and his revolutionary impact on Indian cricket."],
];

const indiancitieswithhints = [
    ["mumbai", "Financial Capital Of India"],
    ["delhi", "Capital Of India"],
    ["bengaluru", "Silicon Valley Of India"],
    ["chennai", "Gateway To South India"],
    ["hyderabad", "City Of Pearls"],
    ["kolkata", "City Of Joy"],
    ["pune", "Oxford Of The East"],
    ["ahmedabad", "Textile Hub Of India"],
    ["jaipur", "Pink City Of Rajasthan"],
    ["surat", "Diamond City"],
    ["lucknow", "City Of Nawabs"],
    ["chandigarh", "Planned City"],
    ["varanasi", "Spiritual Capital Of India"],
    ["amritsar", "Golden Temple City"],
    ["thiruvananthapuram", "Evergreen City Of India"],
    ["kochi", "Queen Of The Arabian Sea"],
    ["mysuru", "City Of Palaces"],
    ["indore", "Cleanest City"],
    ["guwahati", "Gateway To Northeast"],
    ["nagpur", "Orange City"],
    ["patna", "Ancient City"],
    ["bhopal", "City Of Lakes"],
    ["agra", "City Of The Taj Mahal"],
    ["shimla", "Queen Of Hills"],
    ["coimbatore", "Manchester Of India"],
    ["udaipur", "City Of Lakes In Rajasthan"],
    ["vadodara", "Cultural Capital Of Gujarat"],
    ["rajkot", "City Of Saurashtra"],
    ["jodhpur", "Blue City, Mehrangarh Fort"],
    ["madurai", "Temple City, Meenakshi Temple"],
    ["nashik", "Winery Of India, Trimbakeshwar Temple"],
    ["kanpur", "Leather City"],
    ["allahabad", "City Of Triveni, Sangam"],
    ["tiruchirappalli", "Rockfort City, Srirangam Temple"],
    ["aurangabad", "City Of Gates, Ajanta And Ellora Caves"],
    ["ranchi", "City Of Falls, Hundru Falls"],
    ["jamshedpur", "Steel City, Jubilee Park"],
    ["dhanbad", "Coal Capital Of India"],
    ["dehradun", "Doon Valley, Forest Research Institute"],
    ["raipur", "Capital Of Chhattisgarh"],
    ["noida", "IT City"],
    ["ghaziabad", "Industrial Hub Of UP"],
    ["vijayawada", "Business Capital Of Andhra Pradesh"],
    ["visakhapatnam", "City Of Density, RK Beach"],
    ["gwalior", "City Of Forts, Gwalior Fort"],
    ["ludhiana", "Manchester Of India"],
    ["meerut", "Sports Goods Manufacturing Hub"],
    ["salem", "Mangoes And Steel City, Yercaud"],
    ["jabalpur", "City Of Marble, Marble Rocks"],
    ["belagavi", "Sugar Bowl, Kittur Fort"],
    ["rourkela", "Steel City Of Odisha, Hanuman Vatika"],
    ["ajmer", "Holy City, Ajmer Sharif Dargah"],
    ["pondicherry", "French Riviera Of The East, Auroville"],
    ["srinagar", "Paradise On Earth, Dal Lake"],
    ["leh", "Highest Settlement, Pangong Lake"],
    ["shillong", "Scotland Of The East, Elephant Falls"],
    ["imphal", "Jewel Of India, Loktak Lake"],
    ["aizawl", "Land Of Highlanders"],
    ["gangtok", "Buddhist Pilgrimage, Rumtek Monastery"]
];

const indianhistoricalplaceswithhints = [
    ["tajmahal", "Agra - Built By Shah Jahan In Memory Of Mumtaz"],
    ["redfort", "Delhi - Mughal Residence And Military Headquarters"],
    ["qutubminar", "Delhi - Tallest Brick Minaret In The World"],
    ["indiagate", "Delhi - War Memorial For Soldiers Of World War I"],
    ["gatewayofindia", "Mumbai - Commemorates King George V's Visit To India"],
    ["amerfort", "Jaipur - Known For Its Artistic Hindu Architecture"],
    ["hawamahal", "Jaipur - Palace Of Winds With 953 Windows"],
    ["victoriamemorial", "Kolkata - Memorial To Queen Victoria Of Britain"],
    ["charminar", "Hyderabad - Built To Commemorate The End Of A Plague"],
    ["suntemple", "Konark - 13th Century Temple Dedicated To The Sun God"],
    ["khajurahotemples", "Madhya Pradesh - Famous For Erotic Sculptures"],
    ["sanchistupa", "Madhya Pradesh - Built By Emperor Ashoka, Buddhist Relic"],
    ["ajantacaves", "Maharashtra - Ancient Buddhist Cave Paintings And Sculptures"],
    ["elloracaves", "Maharashtra - Rock-Cut Temples And Monasteries"],
    ["mehraulianarchaeologicalpark", "Delhi - Contains Ruins From Several Historical Eras"],
    ["golcondafort", "Hyderabad - Known For Its Acoustic Effects"],
    ["mysorepalace", "Mysuru - Former Residence Of Wodeyar Dynasty"],
    ["fatehpursikri", "Uttar Pradesh - Mughal Emperor Akbar's Capital City"],
    ["raniikavav", "Gujarat - UNESCO World Heritage Stepwell"],
    ["chittorgarhfort", "Rajasthan - Largest Fort In India, Known For Its History Of Valor"],
    ["jallianwalabagh", "Amritsar - Site Of The 1919 Massacre During British Rule"],
    ["brihadeeswarartemple", "Tamil Nadu - Chola Dynasty Temple, UNESCO Site"],
    ["gwaliorfort", "Madhya Pradesh - Historic Fort With Intricate Architecture"],
    ["ranthamborefort", "Rajasthan - Famous Fort Inside A Wildlife Sanctuary"],
    ["elephantacaves", "Mumbai - Ancient Hindu Cave Sculptures"],
    ["ruinsofhampi", "Karnataka - Ancient City, Capital Of Vijayanagara Empire"],
    ["jantarmantar", "Jaipur - Collection Of Astronomical Instruments"],
    ["sabarmatiashram", "Ahmedabad - Mahatma Gandhi's Home And Headquarters"],
    ["nalanduniversity", "Bihar - Ancient Center Of Learning And Buddhism"],
    ["golgumbaz", "Bijapur - Second Largest Dome In The World"],
    ["jogfalls", "Karnataka - One Of The Highest Waterfalls In India"],
    ["cellularjail", "Andaman Islands - Used By British For Political Prisoners"],
    ["raghuwarfort", "Chhattisgarh - Historic Fort With Rich History"],
    ["badshahibagh", "Agra - Mughal Garden With Beautiful Landscapes"],
    ["durgabari", "Silchar - Historical Temple Dedicated To Goddess Durga"],
    ["srirangamtemple", "Tiruchirappalli - Famous Vaishnavite Temple Complex"],
    ["madhuratemple", "Kerala - Temple Known For Its Architectural Splendor"],
    ["seemachalamtemple", "Visakhapatnam - Ancient Temple Dedicated To Varaha Lakshmi Narasimha"],
    ["kumbhalgarhfort", "Rajasthan - Known For Its Impressive Fortifications"],
    ["sahastra lingatemple", "Bagalkot - Temple With Thousand Lingas"],
    ["shantiastupa", "Rajgir - Buddhist Stupa Built By The Japanese"],
    ["rajarani temple", "Bhubaneswar - Ancient Hindu Temple Known For Its Architecture"],
    ["kailasanathtemple", "Kanchipuram - Historic Temple From The Pallava Dynasty"],
    ["sabarimala", "Kerala - Famous Pilgrimage Site In The Western Ghats"],
    ["siddhivinayaktemple", "Mumbai - Popular Ganesh Temple"],
    ["krishna temple", "Udupi - Important Pilgrimage Site For Followers Of Krishna"],
    ["ahmedshahi", "Jaipur - Mughal Period Monument Known For Its Historical Importance"],
    ["pattadakal", "Karnataka - UNESCO World Heritage Site With Chalukyan Temples"],
    ["raigadh", "Maharashtra - Fort Associated With Chhatrapati Shivaji Maharaj"],
    ["shillong", "Shillong - Famous For Its Beautiful Waterfalls"],
    ["mandu", "Madhya Pradesh - Fort City With Rich Historical Significance"],
    ["kalapathar", "Andaman - Known For Its Scenic Beauty And Historical Importance"]
];

const indiancuisineswithhints = [
    ["biryani", "A RICE DISH WITH SPICES, ORIGINATING FROM HYDERABAD"],
    ["samosa", "FRIED PASTRY FILLED WITH SPICED POTATOES"],
    ["dosa", "A TYPE OF THIN CREPE FROM SOUTH INDIA"],
    ["butterchicken", "CREAMY CHICKEN CURRY FROM PUNJAB"],
    ["idli", "STEAMED RICE CAKES FROM SOUTH INDIA"],
    ["paneerbuttermasala", "COTTAGE CHEESE IN A CREAMY TOMATO SAUCE"],
    ["cholebhature", "SPICY CHICKPEAS SERVED WITH FRIED BREAD"],
    ["pavbhaji", "MIXED VEGETABLE CURRY SERVED WITH BUTTERED BREAD"],
    ["dalmakhani", "LENTIL DISH FROM PUNJAB, COOKED WITH BUTTER"],
    ["vada", "SPICY DEEP FRIED SNACK FROM SOUTH INDIA"],
    ["ragdapattice", "SPICY POTATO CAKES WITH A CHICKPEA CURRY"],
    ["kebab", "GRILLED MEAT OR VEGETABLES MARINATED IN SPICES"],
    ["kheer", "SWEET RICE PUDDING COOKED WITH MILK AND DRIED FRUITS"],
    ["poha", "FLATTENED RICE COOKED WITH SPICES AND VEGETABLES"],
    ["pulao", "RICE DISH COOKED WITH SPICES AND VEGETABLES"],
    ["kulfi", "INDIAN ICE CREAM MADE WITH MILK AND FLAVORS"],
    ["bhelpuri", "PUFFED RICE MIXED WITH VEGETABLES AND CHUTNEYS"],
    ["aalotikki", "SPICY POTATO PATTIES OFTEN SERVED WITH CHUTNEY"],
    ["panchmeldal", "MIXED LENTIL CURRY FROM RAJASTHAN"],
    ["daltadka", "LENTIL DISH TEMPERED WITH SPICES AND GHEE"],
    ["aalogobhi", "POTATO AND CAULIFLOWER CURRY"],
    ["kachori", "SPICY FILLED PASTRY OFTEN SERVED AS A SNACK"],
    ["misalpav", "SPICY BEAN CURRY SERVED WITH BREAD"],
    ["khichdi", "RICE AND LENTIL DISH COOKED TOGETHER"],
    ["tandoorichicken", "CHICKEN MARINATED IN YOGURT AND SPICES THEN GRILLED"],
    ["pithla", "SPICY GRAM FLOUR CURRY FROM MAHARASHTRA"],
    ["dhokla", "STEAMED SAVORY CAKE FROM GUJARAT"],
    ["kothimbirvadi", "CORIANDER AND SPICE FLAVORED SNACK FROM MAHARASHTRA"],
    ["prawncurry", "SPICY CURRY MADE WITH PRAWNS"],
    ["sambhar", "TANGY LENTIL STEW FROM SOUTH INDIA"],
    ["khoya", "MILK SOLIDS USED IN SWEETS AND DESSERTS"]
];

const bollywoodmovieswithhints = [
    ["sholay", "An action-packed tale of two criminals hired to fight a notorious bandit."],
    ["dangal", "A story of a father training his daughters to become world-class wrestlers."],
    ["mughaleazam", "An epic love story set against the backdrop of the Mughal empire."],
    ["3idiots", "A heartwarming story about friendship and the pursuit of true passion."],
    ["dilwaledulhanialejayenge", "A romance that blossomed during a trip across Europe."],
    ["lagaan", "Villagers challenge the British to a game of cricket to escape a harsh tax."],
    ["zindaginamilegidobara", "Three friends embark on a road trip that changes their lives."],
    ["kabhikhushikabhiegham", "A family drama about relationships, traditions, and values."],
    ["bhaagmilkhabhaag", "A biopic of an Indian athlete overcoming the odds to become a champion."],
    ["pk", "An alien on Earth questions religion and societal norms."],
    ["bahubali", "A grand tale of royal intrigue and the quest for a throne."],
    ["kalhonaho", "A story of love and heartbreak, with a message of living life to the fullest."],
    ["sultan", "A wrestler rises to fame, facing personal and professional challenges."],
    ["barfi", "A heartwarming tale of a deaf-mute man and his unique love story."],
    ["chakdeindia", "A disgraced hockey player coaches a women's team to World Cup victory."],
    ["gullyboy", "A street rapper rises from the slums to stardom in the Indian hip-hop scene."],
    ["raees", "A bootlegger's rise to power in Gujarat, clashing with law and morality."],
    ["dilse", "A radio journalist falls in love with a mysterious woman with a hidden agenda."],
    ["black", "A touching story of a teacher's bond with a deaf-blind girl."],
    ["devdas", "A tragic tale of unrequited love and the journey of self-destruction."],
    ["humaapkehainkoun", "A family drama revolving around love, marriage, and traditional values."],
    ["veerzaara", "A cross-border love story between an Indian Air Force officer and a Pakistani woman."],
    ["omshantiom", "A story of reincarnation and revenge in the glamorous world of Bollywood."],
    ["tanuwedsmanu", "A quirky love story between two very different personalities."],
    ["andhadhun", "A blind pianist unwittingly becomes embroiled in a murder mystery."],
    ["padmaavat", "An epic drama about the valor of Queen Padmavati and the siege of her kingdom."],
    ["sanju", "A biopic of the controversial life of Bollywood actor Sanjay Dutt."],
    ["badlapur", "A man seeks revenge for the death of his wife and child."],
    ["super30", "A story of a mathematician helping underprivileged kids crack IIT entrance exams."],
    ["war", "Two elite soldiers clash in a fast-paced action thriller."],
    ["msdhoni", "A biopic on the life of Indian cricketer Mahendra Singh Dhoni."],
    ["stree", "A horror-comedy where a village is haunted by a mysterious woman."],
    ["rajhirani", "A biopic on the famous Bollywood actor turned politician, Balasaheb Thackeray."],
    ["gangsofwasseypur", "A gritty saga of power struggles in the coal mafia of Wasseypur."],
    ["article15", "A cop investigates a case of caste-based discrimination and violence."],
    ["uri", "A dramatization of India's surgical strike on terror launch pads."],
    ["parmanu", "A retelling of India's nuclear tests in 1998."],
    ["thappad", "A woman reconsiders her marriage after her husband slaps her in public."],
    ["mirzapur", "A web series about crime, power, and politics in a small Indian town. [Amazon Prime Video]"],
    ["scam1992", "A web series about the rise and fall of stockbroker Harshad Mehta. [SonyLIV]"],
    ["sacredgames", "A cop uncovers a hidden conspiracy with criminal underworld links. [Netflix]"],
    ["familyman", "A web series about a government agent balancing family life with national security threats. [Amazon Prime Video]"],
    ["pataallok", "A web series following a cop investigating a high-profile murder. [Amazon Prime Video]"],
    ["madeinheaven", "A web series about two wedding planners navigating love and deceit in high society. [Amazon Prime Video]"],
    ["bardofblood", "A web series about an ex-spy's dangerous mission in Balochistan. [Netflix]"],
    ["asur", "A web series blending mythology with a psychological crime thriller. [Voot]"],
    ["aperfectmurder", "A web series that intertwines love and crime. [Zee5]"],
    ["insideedge", "A web series about the politics and corruption in cricket leagues. [Amazon Prime Video]"],
    ["crashcourse", "A web series following the intense competition and rivalries in coaching institutes. [Amazon Prime Video]"],
    ["delhicrime", "A web series based on the infamous 2012 Delhi gang-rape case. [Netflix]"],
    ["kohrra", "A web series unraveling a murder mystery in Punjab. [Netflix]"],
    ["fourmoreshotsplease", "A web series about four women navigating life, love, and career. [Amazon Prime Video]"],
    ["breathe", "A web series about a father going to extreme lengths to save his son. [Amazon Prime Video]"],
    ["taandav", "A political web series revolving around power struggles in India. [Amazon Prime Video]"],
    ["specialops", "A web series following an intelligence officer hunting a terrorist mastermind. [Hotstar]"],
    ["hostages", "A web series about a surgeon's family taken hostage before a critical surgery. [Hotstar]"],
    ["classof83", "A web series about a police officer training a group of young cadets. [Netflix]"]
];

let youtuberswithhints = [
    ["carryminati", "Known for his comedic skits, roasting, and humorous commentary, this YouTuber gained massive popularity with his energetic personality and quirky content."],
    ["ashishchanchlanivines", "This YouTuber creates relatable and hilarious short skits, often focusing on everyday situations in Indian households, which have gained him a massive following."],
    ["amitbhadana", "This YouTuber from Haryana is known for his comedic sketches and relatable, family-friendly humor, focusing on daily life in India."],
    ["bbkivines", "One of India's biggest YouTube stars, this YouTuber's characters and hilarious storytelling, often involving friends and family, have earned him a huge fan base."],
    ["techburner", "A tech enthusiast who presents unboxing, reviews, and tutorials in a fun, engaging way, often using humor to make tech accessible to the masses."],
    ["technicalguruji", "This YouTuber is known for his simple, straightforward tech reviews and updates, focusing on gadgets and smartphone launches."],
    ["slayypoint", "A duo that gained popularity with their funny commentary and roasting videos, often poking fun at cringe-worthy content and trends on social media."],
    ["mostlysane", "This YouTuber creates content focused on everyday life, often portraying multiple characters in her skits to bring out the humor in Indian family dynamics."],
    ["mumbikernikhil", "A lifestyle and travel vlogger, known for his engaging videos about motorcycling, traveling across India, and his daily life updates."],
    ["flyingbeast", "This YouTuber is a pilot and fitness enthusiast who vlogs about his personal life, travels, and fitness journey, often featuring his family."],
    ["tanmaybhat", "A stand-up comedian and former AIB member, this YouTuber now focuses on gaming, reaction videos, and humorous takes on internet trends."],
    ["beerbiceps", "A lifestyle and fitness coach who shares content on self-improvement, fitness tips, and entrepreneurial advice, often hosting interviews with various celebrities."],
    ["triggeredinsaan", "A popular roasting channel where this YouTuber reacts humorously to viral videos, movies, and cringe content, often with sarcastic commentary."],
    ["sandeepmaheshwari", "A motivational speaker who shares life lessons, inspiration, and practical advice for success and self-improvement, appealing to a large audience."],
    ["emivlog", "Known for creating comedic skits and personal vlogs that explore everyday problems, social issues, and humorous takes on daily life."],
    ["facttechz", "This YouTuber focuses on sharing interesting facts, mysterious stories, and strange phenomena, making knowledge and trivia entertaining for his audience."],
    ["garimachaurasia", "A social media influencer and YouTuber, famous for her TikTok videos and now known for her lifestyle vlogs and entertaining dance videos."],
    ["ashokbhatia", "This YouTuber shares insightful videos about the stock market, personal finance, and investment strategies, catering to finance enthusiasts."],
    ["dhruvrathee", "A prominent YouTuber known for his detailed political and social commentary, this creator analyzes current affairs and environmental issues with a critical perspective."],
    ["anaysa", "A beauty and lifestyle YouTuber who shares makeup tutorials, skincare routines, and fashion tips, appealing to a largely female audience."],
    ["yogasy", "This YouTuber provides yoga tutorials, mindfulness techniques, and holistic wellness advice, helping viewers achieve physical and mental well-being."],
    ["prajaktakoli", "A comedian and lifestyle vlogger, known for her funny and relatable skits about Indian families, dating, and social life."],
    ["bheemkavacha", "A popular YouTuber known for creating animated videos around historical events and mythical stories, often drawing inspiration from Indian epics."],
    ["gauravzone", "This YouTuber creates lifestyle, travel, and personal vlogs, often showcasing his daily life, adventures, and fun challenges with friends."],
    ["shivanshubisht", "A digital creator who shares content related to daily fitness, inspirational vlogs, and motivational speaking, focusing on self-discipline and personal growth."],
    ["mythpat", "A gaming YouTuber known for his humorous gameplay commentary, often creating funny content around trending video games like GTA V and Minecraft."],
    ["neetubisht", "A lifestyle YouTuber known for her vlogs, which focus on beauty, fashion, and her personal life, giving a peek into her daily routine."],
    ["mrandmisstech", "This YouTube couple shares tech reviews, unboxing, and tips on various gadgets and apps, making technology more relatable and accessible for their audience."],
    ["khangsresearch", "This YouTuber focuses on educational content, particularly around civil services exam preparation, and offers tips and knowledge for aspirants."],
    ["gauravtaneja", "A professional pilot and fitness enthusiast, this YouTuber shares insights into his daily life, fitness routines, and travel adventures."],
    ["krkboxoffice", "Known for his controversial and sarcastic movie reviews, this YouTuber makes headlines with his bold takes on Bollywood films and actors."],
    ["nikinbhat", "An educational YouTuber focusing on programming tutorials, tech reviews, and tips for aspiring developers and tech enthusiasts."],
    ["f2freestylers", "A football YouTube channel featuring impressive freestyle tricks, challenges, and entertaining skits related to football culture."],
    ["ashishsandeep", "A travel vlogger known for his adventurous journeys, exploring offbeat locations and sharing tips for budget travel."],
    ["mumbaikarnikhil", "This vlogger shares daily life experiences, travel adventures, and fun challenges with a focus on relatable Indian content."],
    ["round2hell", "A group of friends known for their hilarious short films and skits, often depicting humorous situations in everyday life."],
    ["elvishyadav", "A comedian and vlogger known for his funny sketches, often portraying relatable characters in various comedic scenarios."],
    ["techno gamerz", "A gaming YouTuber who focuses on gameplay, walkthroughs, and tutorials for popular games like PUBG Mobile and Free Fire."],
    ["sandeepmishra", "An educational and tech YouTuber, sharing insights into programming, artificial intelligence, and technology trends."],
    ["gamingwithnishant", "A popular gaming channel featuring entertaining gameplay, tutorials, and live streams of trending video games."],
    ["lokeshraja", "A vlogger known for his travel content, showcasing stunning locations, food experiences, and local cultures in his videos."],
    ["princechoudhary", "A gaming YouTuber specializing in live streams, gameplay commentary, and engaging with fans through various gaming content."],
    ["alankritagiri", "A lifestyle and travel vlogger known for sharing experiences and tips on traveling, food, and culture."],
    ["ankitbhati", "A prominent gaming YouTuber known for his humorous gameplay and entertaining commentary on popular games."],
    ["nehanayak", "A vlogger focusing on lifestyle, beauty, and wellness, sharing personal stories and experiences with her audience."],
    ["kashishsaini", "A gaming YouTuber who shares gameplay, tips, and tricks for popular games, engaging a large gaming community."],
    ["gyaanendrop", "A YouTuber known for his content on Free Fire gameplay, including tips, tricks, and live streams, catering to the game's passionate community."],
    ["desigamers", "A popular Free Fire content creator who shares gameplay, tips, and challenges, engaging a large audience of fans and gamers."],
    ["totalgaming", "One of the top Free Fire players and content creators in India, known for his high-skill gameplay and entertaining commentary."],
    ["brawlhalla", "An esports player known for participating in various gaming tournaments and sharing insights and highlights from competitive gameplay."],
    ["iFlickz", "An esports player specializing in BGMI content, sharing gameplay, tips, and strategies for fellow players."],
    ["scoutop", "A professional BGMI esports player who showcases gameplay, strategies, and tips through entertaining live streams and videos."],
    ["dynamo", "One of India's most popular BGMI streamers and content creators, known for his skills and entertaining live commentary."],
    ["kaalra", "A prominent BGMI player who shares gameplay, tips, and reviews, engaging a growing community of gamers."],
    ["beastboyshub", "A gaming YouTuber known for his entertaining gameplay, live streams, and humorous commentary, particularly in games like Free Fire."],
    ["jonathangaming", "An esports player known for his exceptional skills in BGMI and engaging gameplay content, often showcasing competitive matches."],
    ["souravjoshi", "A popular vlogger known for his lifestyle content, travel experiences, and engaging storytelling that resonates with a wide audience."],
    ["lakshaychaudhary", "A gaming YouTuber who shares gameplay, tips, and entertaining commentary, focusing on a variety of games."],
    ["thugesh", "A comedy YouTuber known for his hilarious skits and parodies, often commenting on social issues and pop culture."],
];
